#!/bin/sh
set -e

export SDKROOT=$(xcrun --show-sdk-path)
export ARCH=$1

# Binaries
export CC=$(xcrun --find gcc)
export CPP=$(xcrun --find gcc)" -E"
export CXX=$(xcrun --find g++)
export LD=$(xcrun --find ld)

# Flags
export CFLAGS="$CFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include"
export CPPFLAGS="$CPPFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include"
export CXXFLAGS="$CXXFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include"
export LDFLAGS="$LDFLAGS -arch $ARCH -isysroot $SDKROOT -L$PREFIX/lib"

export PREFIX
export PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR

# Remove script parameters
shift 1

export ac_cv_func_malloc_0_nonnull=yes
export ac_cv_func_realloc_0_nonnull=yes

./configure \
	--prefix="$PREFIX" \
	--host="$CHOST" \
	--enable-static \
	--disable-shared \
	$@
